### ISSUE TITLE
How do i resolve this circular dependency issue. 

### ISSUE THREAD

**Issue by orar** [fb55/htmlparser2#256] opened 2018-10-28 09:40 UTC
This circular dependency breaks my bundle anytime and i have no idea about it

```
(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/FeedHandler.js -> node_modules/htmlparser2/lib/index.js
(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/FeedHandler.js -> commonjs-proxy:/home/orar/workspace/npmlab/questrar/node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/index.js
(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/Stream.js -> node_modules/htmlparser2/lib/index.js
(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/ProxyHandler.js -> node_modules/htmlparser2/lib/index.js
(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/CollectingHandler.js -> node_modules/htmlparser2/lib/index.js

```
And i get the follow error when i run my bundle
```
 var DomHandler$1 = lib.DomHandler;
                               ^
TypeError: Cannot read property 'DomHandler' of undefined
```

**Comment by GreenGremlin** [comment] 2019-01-30 18:32
I believe this is a duplicate of  #223, which has been fixed.

**Comment by fniewijk** [comment] 2019-02-08 12:53
When is this going to be released?

**Comment by fb55** [comment] 2019-02-17 19:55
It has been released!

**Closed by fb55** 2019-02-17 19:55 UTC
