### ISSUE TITLE
error TS1005: ',' expected.

### ISSUE THREAD

**Issue by yiduan-logicloop** [fb55/htmlparser2#1271] opened 2022-08-19 01:11 UTC
I got this error when I use [html-react-parser](https://www.npmjs.com/package/html-react-parser) which depends on htmlparser2. 

Both html-react-parser 3.0.1 and htmlparser2 8.0.1 are the latest version. So I can't fix this issue by upgrading to a newer version. I find this [post](https://github.com/socketio/socket.io/issues/3916) but my typescript version is 4.1.2 so this does not apply to me.

Do you have any idea how we can fix this?

```
#!/bin/bash -eo pipefail
yarn test

yarn run v1.22.10
$ run-s type-check jest
$ tsc --noEmit --project client/tsconfig.json
node_modules/htmlparser2/lib/index.d.ts:2:23 - error TS1005: ',' expected.

2 export { Parser, type ParserOptions };
                        ~~~~~~~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:4:27 - error TS1005: ',' expected.

4 export { DomHandler, type DomHandlerOptions };
                            ~~~~~~~~~~~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:32:37 - error TS1005: ',' expected.

32 export { default as Tokenizer, type Callbacks as TokenizerCallbacks, } from "./Tokenizer.js";
                                       ~~~~~~~~~


Found 3 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "type-check" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by fb55** [comment] 2022-08-19 06:23
Duplicate of #1237. See #1237 (comment) for some suggestions for how to work around this.

**Comment by fb55** [comment] 2022-08-19 06:24
You'll have to update TypeScript. See #1237 (comment) for some suggestions for how to work around this.

**Closed** 2022-08-19 06:24 UTC
